[package]
name = "educhain-scholarships"
version = "0.1.0"
edition = "2021"
description = "EduChain Scholarships - Microfinance tool on Stellar for crowdfunding education"
authors = ["EduChain Team"]

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "20.0.0"
soroban-token-sdk = "20.0.0"

[dev_dependencies]
soroban-sdk = { version = "20.0.0", features = ["testutils"] }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
